# Change these first
owner: BarkleyREI # Your GitHub username
repo: ArchiTECH-upptime # Your Github repository name

# Add your sites here
sites:
  - name: ArchiTECH Service
    url: https://www.builtforyou.com/ping.html
  - name: Architech Help
    url: https://www.architech.help/ping.html
  - name: Allegany County, The Mountain Side of Maryland
    url: https://www.mdmountainside.com/ping.html
  - name: PA Route 6 Alliance
    url: https://www.paroute6.com/ping.html
  - name: Raystown Lake
    url: https://www.raystown.org/ping.html
  - name: Visit Santa Rosa
    url: https://www.visitsantarosa.com/ping.html
  - name: Visit the Delta
    url: https://www.visitthedelta.com/ping.html
  - name: Visit Vicksburg
    url: https://www.visitvicksburg.com/ping.html
  - name: University of Virginia School of Architecture
    url: https://www.arch.virginia.edu/ping.html
  - name: LuCa National Training Network
    url: https://www.lucatraining.org/ping.html

assignees: # Users to assign downtime issues (optional)
  - risadams

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.architech.network
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/BarkleyREI/ArchiTECH-upptime/master/architech-logo.png
  name: ArchiTECH
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: ArchiTECH
      href: https://www.builtforyou.com/

i18n:
  footer: Copyright © 2020 BarkleyREI

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
