# Change these first
owner: BarkleyREI # Your GitHub username
repo: ArchiTECH-upptime # Your Github repository name

# Add your sites here
sites:
  # Platform Sites
  - name: ArchiTECH Service
    url: https://www.builtforyou.com/ping.html
    icon: https://cdn1.architech.network/at-assets/1.0.0.0/img/admin/favicons/favicon-96x96.png

  - name: ArchiTECH Tourism
    url: https://architech.travel/ping.html
    icon: https://cdn1.architech.network/at-assets/1.0.0.0/img/admin/favicons/favicon-96x96.png

  - name: Architech Help
    url: https://www.architech.help/ping.html
    icon: https://cdn1.architech.network/at-assets/1.0.0.0/img/admin/favicons/favicon-96x96.png
  - name: Architech Help - search
    url: https://www.architech.help/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  # Tenant Sites
  - name: Allegany County, The Mountain Side of Maryland
    url: https://www.mdmountainside.com/ping.html
  - name: Allegany County, The Mountain Side of Maryland - Search
    url: https://www.mdmountainside.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: PA Route 6 Alliance
    url: https://www.paroute6.com/ping.html
  - name: PA Route 6 Alliance - Search
    url: https://www.paroute6.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Raystown Lake
    url: https://www.raystown.org/ping.html
  - name: Raystown Lake - Search
    url: https://www.raystown.org/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Visit Santa Rosa
    url: https://www.visitsantarosa.com/ping.html
  - name: Visit Santa Rosa - Search
    url: https://www.visitsantarosa.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Visit the Delta
    url: https://www.visitthedelta.com/ping.html
  - name: Visit the Delta - Search
    url: https://www.visitthedelta.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Visit Vicksburg
    url: https://www.visitvicksburg.com/ping.html
  - name: Visit Vicksburg - search
    url: https://www.visitvicksburg.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: University of Virginia School of Architecture
    url: https://www.arch.virginia.edu/ping.html
  - name: University of Virginia School of Architecture - search
    url: https://www.arch.virginia.edu/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: LuCa National Training Network
    url: https://www.lucatraining.org/ping.html
  - name: LuCa National Training Network - search
    url: https://www.lucatraining.org/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

# Demo Sites
  - name: Redwood
    url: https://demo-redwood-v1.builtforyou.com/ping.html
  - name: Redwood - Search
    url: https://demo-redwood-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Pine Ridge
    url: https://demo-pineridge-v1.builtforyou.com/ping.html
  - name: Pine Ridge - Search
    url: https://demo-pineridge-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Everest
    url: https://everest.builtforyou.com/ping.html
  - name: Everest - Search
    url: https://everest.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Outdoors
    url: https://demo-outdoors-v1.builtforyou.com/ping.html
  - name: Outdoors - Search
    url: https://demo-outdoors-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Coastal
    url: https://demo-coastal-v1.builtforyou.com/ping.html
  - name: Coastal - Search
    url: https://demo-coastal-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Winter
    url: https://demo-winter-v1.builtforyou.com/ping.html
  - name: Winter - Search
    url: https://demo-winter-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Winter
    url: https://demo-winter-v1.builtforyou.com/ping.html
  - name: Winter - Search
    url: https://demo-winter-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Bear's Woods
    url: https://demo-bearswoods-v1.builtforyou.com/ping.html
  - name: Bear's Woods - Search
    url: https://demo-bearswoods-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Norcal
    url: https://demo-norcal-v1.builtforyou.com/ping.html
  - name: Norcal - Search
    url: https://demo-norcal-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Adventure
    url: https://demo-adventure-v1.builtforyou.com/ping.html
  - name: Adventure - Search
    url: https://demo-adventure-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Lybart College
    url: https://demo-lybart-v1.builtforyou.com/ping.html
  - name: Lybart College - Search
    url: https://demo-lybart-v1.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

  - name: Lybart College (v2)
    url: https://demo-lybart-v2.builtforyou.com/ping.html
  - name: Lybart College (v2) - Search
    url: https://demo-lybart-v2.builtforyou.com/results?search=
    __dangerous__body_degraded: "Search service is unavailable"

assignees: # Users to assign downtime issues (optional)
  - risadams

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.architech.network
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/BarkleyREI/ArchiTECH-upptime/master/architech-logo.png
  name: ArchiTECH
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: ArchiTECH
      href: https://www.builtforyou.com/

i18n:
  footer: Copyright © 2020 BarkleyREI
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
